/* generated by tools/switch_gl_resolve.py from build/switch/gen/gl_imports.list; do not edit */
#include <EGL/egl.h>
#include <GLES3/gl32.h>
#include <GLES2/gl2ext.h>
#include <string.h>

/* hand-written in host_shader_cache.c: the shader pack (programs
compiled ahead on another core, the game's program names mapped to
them, deferred compiles) and glShaderSource's unwrapping of the
guest's widened string pointers */
extern char hostgl_glShaderSource[];
extern char hostgl_glCompileShader[];
extern char hostgl_glGetShaderiv[];
extern char hostgl_glGetShaderInfoLog[];
extern char hostgl_glCreateProgram[];
extern char hostgl_glAttachShader[];
extern char hostgl_glBindAttribLocation[];
extern char hostgl_glLinkProgram[];
extern char hostgl_glGetProgramiv[];
extern char hostgl_glGetProgramInfoLog[];
extern char hostgl_glUseProgram[];
extern char hostgl_glGetUniformLocation[];

static const struct { const char *name; void *function; } kHostGlFunctions[] = {
	{"hostgl_glGetIntegerv", (void *)glGetIntegerv},
	{"hostgl_glCopyImageSubData", (void *)glCopyImageSubData},
	{"hostgl_glGenerateMipmap", (void *)glGenerateMipmap},
	{"hostgl_glGetError", (void *)glGetError},
	{"hostgl_glEnable", (void *)glEnable},
	{"hostgl_glDisable", (void *)glDisable},
	{"hostgl_glViewport", (void *)glViewport},
	{"hostgl_glDepthRangef", (void *)glDepthRangef},
	{"hostgl_glScissor", (void *)glScissor},
	{"hostgl_glClearColor", (void *)glClearColor},
	{"hostgl_glClearDepthf", (void *)glClearDepthf},
	{"hostgl_glClearStencil", (void *)glClearStencil},
	{"hostgl_glClear", (void *)glClear},
	{"hostgl_glColorMask", (void *)glColorMask},
	{"hostgl_glDepthMask", (void *)glDepthMask},
	{"hostgl_glDepthFunc", (void *)glDepthFunc},
	{"hostgl_glStencilFunc", (void *)glStencilFunc},
	{"hostgl_glStencilOp", (void *)glStencilOp},
	{"hostgl_glStencilMask", (void *)glStencilMask},
	{"hostgl_glBlendFunc", (void *)glBlendFunc},
	{"hostgl_glBlendEquation", (void *)glBlendEquation},
	{"hostgl_glBlendColor", (void *)glBlendColor},
	{"hostgl_glCullFace", (void *)glCullFace},
	{"hostgl_glFrontFace", (void *)glFrontFace},
	{"hostgl_glPolygonOffset", (void *)glPolygonOffset},
	{"hostgl_glLineWidth", (void *)glLineWidth},
	{"hostgl_glPixelStorei", (void *)glPixelStorei},
	{"hostgl_glReadPixels", (void *)glReadPixels},
	{"hostgl_glFinish", (void *)glFinish},
	{"hostgl_glFlush", (void *)glFlush},
	{"hostgl_glGenTextures", (void *)glGenTextures},
	{"hostgl_glDeleteTextures", (void *)glDeleteTextures},
	{"hostgl_glBindTexture", (void *)glBindTexture},
	{"hostgl_glActiveTexture", (void *)glActiveTexture},
	{"hostgl_glTexImage2D", (void *)glTexImage2D},
	{"hostgl_glTexImage3D", (void *)glTexImage3D},
	{"hostgl_glTexSubImage2D", (void *)glTexSubImage2D},
	{"hostgl_glCompressedTexImage2D", (void *)glCompressedTexImage2D},
	{"hostgl_glCompressedTexImage3D", (void *)glCompressedTexImage3D},
	{"hostgl_glTexParameteri", (void *)glTexParameteri},
	{"hostgl_glTexParameteriv", (void *)glTexParameteriv},
	{"hostgl_glTexParameterf", (void *)glTexParameterf},
	{"hostgl_glTexParameterfv", (void *)glTexParameterfv},
	{"hostgl_glGenSamplers", (void *)glGenSamplers},
	{"hostgl_glBindSampler", (void *)glBindSampler},
	{"hostgl_glSamplerParameteri", (void *)glSamplerParameteri},
	{"hostgl_glSamplerParameterf", (void *)glSamplerParameterf},
	{"hostgl_glSamplerParameterfv", (void *)glSamplerParameterfv},
	{"hostgl_glGenFramebuffers", (void *)glGenFramebuffers},
	{"hostgl_glDeleteFramebuffers", (void *)glDeleteFramebuffers},
	{"hostgl_glBindFramebuffer", (void *)glBindFramebuffer},
	{"hostgl_glFramebufferTexture2D", (void *)glFramebufferTexture2D},
	{"hostgl_glCheckFramebufferStatus", (void *)glCheckFramebufferStatus},
	{"hostgl_glBlitFramebuffer", (void *)glBlitFramebuffer},
	{"hostgl_glDrawBuffers", (void *)glDrawBuffers},
	{"hostgl_glReadBuffer", (void *)glReadBuffer},
	{"hostgl_glInvalidateFramebuffer", (void *)glInvalidateFramebuffer},
	{"hostgl_glGenBuffers", (void *)glGenBuffers},
	{"hostgl_glDeleteBuffers", (void *)glDeleteBuffers},
	{"hostgl_glBindBuffer", (void *)glBindBuffer},
	{"hostgl_glBufferData", (void *)glBufferData},
	{"hostgl_glBufferSubData", (void *)glBufferSubData},
	{"hostgl_glBindBufferBase", (void *)glBindBufferBase},
	{"hostgl_glBindBufferRange", (void *)glBindBufferRange},
	{"hostgl_glGenVertexArrays", (void *)glGenVertexArrays},
	{"hostgl_glBindVertexArray", (void *)glBindVertexArray},
	{"hostgl_glEnableVertexAttribArray", (void *)glEnableVertexAttribArray},
	{"hostgl_glDisableVertexAttribArray", (void *)glDisableVertexAttribArray},
	{"hostgl_glVertexAttribPointer", (void *)glVertexAttribPointer},
	{"hostgl_glVertexAttribIPointer", (void *)glVertexAttribIPointer},
	{"hostgl_glVertexAttrib4fv", (void *)glVertexAttrib4fv},
	{"hostgl_glVertexAttribI4ui", (void *)glVertexAttribI4ui},
	{"hostgl_glDrawArrays", (void *)glDrawArrays},
	{"hostgl_glDrawElements", (void *)glDrawElements},
	{"hostgl_glDrawElementsBaseVertex", (void *)glDrawElementsBaseVertex},
	{"hostgl_glCreateShader", (void *)glCreateShader},
	{"hostgl_glShaderSource", (void *)hostgl_glShaderSource},
	{"hostgl_glCompileShader", (void *)hostgl_glCompileShader},
	{"hostgl_glGetShaderiv", (void *)hostgl_glGetShaderiv},
	{"hostgl_glGetShaderInfoLog", (void *)hostgl_glGetShaderInfoLog},
	{"hostgl_glDeleteShader", (void *)glDeleteShader},
	{"hostgl_glCreateProgram", (void *)hostgl_glCreateProgram},
	{"hostgl_glAttachShader", (void *)hostgl_glAttachShader},
	{"hostgl_glBindAttribLocation", (void *)hostgl_glBindAttribLocation},
	{"hostgl_glLinkProgram", (void *)hostgl_glLinkProgram},
	{"hostgl_glGetProgramiv", (void *)hostgl_glGetProgramiv},
	{"hostgl_glGetProgramInfoLog", (void *)hostgl_glGetProgramInfoLog},
	{"hostgl_glUseProgram", (void *)hostgl_glUseProgram},
	{"hostgl_glGetUniformLocation", (void *)hostgl_glGetUniformLocation},
	{"hostgl_glUniform1i", (void *)glUniform1i},
	{"hostgl_glUniform1iv", (void *)glUniform1iv},
	{"hostgl_glUniform1f", (void *)glUniform1f},
	{"hostgl_glUniform4fv", (void *)glUniform4fv},
	{"hostgl_glUniform2f", (void *)glUniform2f},
	{"hostgl_glGenQueries", (void *)glGenQueries},
	{"hostgl_glBeginQuery", (void *)glBeginQuery},
	{"hostgl_glEndQuery", (void *)glEndQuery},
	{"hostgl_glGetQueryObjectuiv", (void *)glGetQueryObjectuiv},
};

void *host_gl_resolve(const char *name)
{
	for (unsigned long i = 0; i < sizeof(kHostGlFunctions) / sizeof(kHostGlFunctions[0]); i++)
		if (!strcmp(kHostGlFunctions[i].name, name))
			return kHostGlFunctions[i].function;
	return 0;
}
