/*
GUEST_MAIN.C

Milestone 2 (PORTING.md): exercises the ported musl for real - malloc,
printf (through stdout, so through write() and __guest_syscall), a
snprintf round trip - not just a single hand-crafted host_log call.
*/

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../include/switch_guest_abi.h"

extern void host_log(const char *text);
extern char __guest_image_end[];
/* generated by tools/android_imports.py (build/switch/gen/guest_imports.s) -
one table entry per import, filled by the host at load time; see
switch_guest_abi.h */
extern uint64_t __host_import_table[];
extern char __host_import_names[];
extern const uint32_t __host_import_count;

void __guest_entry(void);

__attribute__((section(".guest_header"), used)) const struct guest_header guest_header = {
	.magic = GUEST_MAGIC,
	.abi_version = GUEST_ABI_VERSION,
	.image_end = (uint32_t)(uintptr_t)__guest_image_end,
	.import_table = (uint32_t)(uintptr_t)__host_import_table,
	.import_names = (uint32_t)(uintptr_t)__host_import_names,
	.import_count = (uint32_t)(uintptr_t)&__host_import_count,
	.entry = (uint32_t)(uintptr_t)__guest_entry,
};

extern void __guest_runtime_init(void);
extern void __guest_tp_init_main_thread(void);

void __guest_entry(void)
{
	/* before anything else - musl's own TLS access (__get_tp, guest_tp.c)
	needs this thread's block set up before any function that might
	touch it, which is nearly everything past this point */
	__guest_tp_init_main_thread();
	__guest_runtime_init();
	host_log("guest entry reached; exercising musl now");

	printf("printf works: %d + %d = %d\n", 2, 2, 2 + 2);
	fflush(stdout);

	char *buf = malloc(128);
	if (!buf)
	{
		host_log("malloc(128) returned NULL");
		return;
	}
	snprintf(buf, 128, "malloc'd at %p, strlen says %zu", buf, strlen("round trip"));
	host_log(buf);
	free(buf);

	/* a few more, to exercise the bump allocator past one block */
	for (int i = 0; i < 8; i++)
	{
		char *p = malloc(4096);
		if (!p)
		{
			host_log("malloc(4096) returned NULL partway through the loop");
			return;
		}
		memset(p, (unsigned char)i, 4096);
		free(p);
	}

	host_log("guest entry done - musl held up");

	/* the real thing: source/shell/shell_xbox.c's own main() - already
	compiled and linked (unlike Vita, which excludes this file since its
	own host provides main instead; nothing excludes it for Switch, so
	it's just sat there as an unused extern symbol until now). Milestone
	10's guest_text_demo() already proved the GL pipeline separately -
	not called here too, to keep whatever happens next unambiguous. */
	/* the game's tick on a thread (and core) of its own, overlapping the
	frame's rendering, as on the Vita (port/linux/game/tick_thread.c) */
	setenv("HALO_TICK_THREAD", "1", 1);
	host_log("calling the game's real main() now");
	extern int main(void);
	main();
	host_log("the game's main() returned (this is not expected in normal play)");
}
