#!/usr/bin/env python3
"""Generate the Switch host's hostgl_<name> -> real GLES3 function table.

Unlike Android (tools/android_gl_stubs.py's --host-table exclusion: it
resolves GL names at runtime via dlsym against a dynamically loaded
libGLESv3.so), this host statically links devkitPro's real libGLESv2.a/
libEGL.a - the real symbols are already link-time addresses, so a plain
name->&function table needs no runtime lookup at all.

Usage: switch_gl_resolve.py gl_imports.list output.c
"""

import sys


# DISABLED 2026-10-05: the shader pack cannot work on this driver, and every
# mechanism it could have used was measured and found missing:
#   * cross-context program sharing - the driver allocates program names from
#     one counter across contexts but does not share the objects, so a name
#     handed between contexts silently names an unrelated program. This is what
#     rendered white geometry and missing enemy models.
#   * program binaries - GL_NUM_PROGRAM_BINARY_FORMATS is 0 on this context,
#     and neither GL_ARB_get_program_binary nor GL_AMD_shader_binary_format is
#     present (log: "nouveau / NV120 / OpenGL ES 3.2 Mesa 20.1.0-rc3").
#   * Mesa's own disk cache - set via MESA_SHADER_CACHE_DISABLE=false and
#     XDG_CACHE_HOME; no cache directory is ever created, because nouveau
#     compiles GLSL through TGSI and does not use the NIR disk cache.
# So there is nowhere for a precompiled program to be built that the game is
# not already waiting on, and the first-appearance hitch cannot be avoided in
# software on this hardware. With this empty, hostgl_gl* resolves straight to
# real GLES3 again, which is where the game worked before the pack existed.
# host_shader_cache.c is kept, unbuilt, for a driver that does cooperate.
# hostgl_glShaderSource stays hand-written, and is NOT part of the shader
# pack: build/switch/gen/guest_gl.c truncates each string pointer to 32 bits
# before widening it into a 64-bit slot, so the host has to unpack the array
# itself. Everything else below used to be intercepted for the pack and now
# goes straight to real GLES3.
#
# The three counters in host_shader_stats.c stay intercepted too, but they
# only forward and bump a number: the frame counter shows the compile stalls,
# which is otherwise invisible while it happens.
CACHE_FUNCTIONS = (
    "hostgl_glShaderSource",
    "hostgl_glCompileShader", "hostgl_glGetShaderiv",
    "hostgl_glLinkProgram",
)


def main():
    imports_list, output = sys.argv[1:3]
    names = [line.split("#", 1)[0].strip() for line in open(imports_list, encoding="utf-8")]
    names = [n for n in names if n]
    out = [
        "/* generated by tools/switch_gl_resolve.py from build/switch/gen/gl_imports.list; do not edit */",
        "#include <EGL/egl.h>",
        "#include <GLES3/gl32.h>",
        "#include <GLES2/gl2ext.h>",
        "#include <string.h>",
        "",
        "/* hand-written in host_shader_cache.c: the shader pack (programs",
        "compiled ahead on another core, the game's program names mapped to",
        "them, deferred compiles) and glShaderSource's unwrapping of the",
        "guest's widened string pointers */",
        *[f"extern char {n}[];" for n in CACHE_FUNCTIONS],
        "",
        "static const struct { const char *name; void *function; } kHostGlFunctions[] = {",
    ]
    for name in names:
        if name in CACHE_FUNCTIONS:
            out.append(f'\t{{"{name}", (void *){name}}},')
            continue
        real = name[len("hostgl_"):]
        out.append(f'\t{{"{name}", (void *){real}}},')
    out += [
        "};",
        "",
        "void *host_gl_resolve(const char *name)",
        "{",
        "\tfor (unsigned long i = 0; i < sizeof(kHostGlFunctions) / sizeof(kHostGlFunctions[0]); i++)",
        "\t\tif (!strcmp(kHostGlFunctions[i].name, name))",
        "\t\t\treturn kHostGlFunctions[i].function;",
        "\treturn 0;",
        "}",
    ]
    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
