#!/usr/bin/env python3
"""Generate the Switch host's hostgl_<name> -> real GLES3 function table.

Unlike Android (tools/android_gl_stubs.py's --host-table exclusion: it
resolves GL names at runtime via dlsym against a dynamically loaded
libGLESv3.so), this host statically links devkitPro's real libGLESv2.a/
libEGL.a - the real symbols are already link-time addresses, so a plain
name->&function table needs no runtime lookup at all.

Usage: switch_gl_resolve.py gl_imports.list output.c
"""

import sys


def main():
    imports_list, output = sys.argv[1:3]
    names = [line.split("#", 1)[0].strip() for line in open(imports_list, encoding="utf-8")]
    names = [n for n in names if n]
    out = [
        "/* generated by tools/switch_gl_resolve.py from build/switch/gen/gl_imports.list; do not edit */",
        "#include <EGL/egl.h>",
        "#include <GLES3/gl32.h>",
        "#include <GLES2/gl2ext.h>",
        "#include <string.h>",
        "",
        "/* glShaderSource's generated guest wrapper (tools/android_gl_stubs.py)",
        "widens each string pointer into a fixed array of 64-bit slots instead",
        "of passing a real const char *const * - the real glShaderSource can't",
        "take that directly, so this unwraps it back into one. */",
        "void hostgl_glShaderSource(GLuint shader, GLsizei count, const unsigned long long *strings,",
        "\tconst GLint *lengths)",
        "{",
        "\tconst char *pointers[16];",
        "\tGLsizei index;",
        "",
        "\tif (count > 16)",
        "\t\tcount = 16;",
        "\tfor (index = 0; index < count; index++)",
        "\t\tpointers[index] = (const char *)(unsigned long)strings[index];",
        "\tglShaderSource(shader, count, pointers, lengths);",
        "}",
        "",
        "/* shader compiles and links, timed: one taking milliseconds in the",
        "middle of a frame is a hitch (a new effect's first appearance) */",
        "#include <switch.h>",
        "extern void logf_both(const char *fmt, ...);",
        "static double s_compile_ms_total;",
        "static unsigned s_compile_count, s_compile_logged;",
        "static void compile_time(const char *what, u64 start)",
        "{",
        "\tdouble ms = (double)armTicksToNs(armGetSystemTick() - start) / 1000000.0;",
        "",
        "\ts_compile_ms_total += ms;",
        "\ts_compile_count++;",
        "\tif (ms >= 2.0 && s_compile_logged < 60)",
        "\t{",
        "\t\ts_compile_logged++;",
        "\t\tlogf_both(\"GL %s took %.1f ms (%u compiles/links so far, %.0f ms in all)\\n\", what, ms,",
        "\t\t\ts_compile_count, s_compile_ms_total);",
        "\t}",
        "}",
        "",
        "void hostgl_glCompileShader(GLuint shader)",
        "{",
        "\tu64 start = armGetSystemTick();",
        "",
        "\tglCompileShader(shader);",
        "\tcompile_time(\"glCompileShader\", start);",
        "}",
        "",
        "void hostgl_glLinkProgram(GLuint program)",
        "{",
        "\tu64 start = armGetSystemTick();",
        "",
        "\tglLinkProgram(program);",
        "\tcompile_time(\"glLinkProgram\", start);",
        "}",
        "",
        "static const struct { const char *name; void *function; } kHostGlFunctions[] = {",
    ]
    for name in names:
        if name in ("hostgl_glShaderSource", "hostgl_glCompileShader", "hostgl_glLinkProgram"):
            out.append(f'\t{{"{name}", (void *){name}}},')
            continue
        real = name[len("hostgl_"):]
        out.append(f'\t{{"{name}", (void *){real}}},')
    out += [
        "};",
        "",
        "void *host_gl_resolve(const char *name)",
        "{",
        "\tfor (unsigned long i = 0; i < sizeof(kHostGlFunctions) / sizeof(kHostGlFunctions[0]); i++)",
        "\t\tif (!strcmp(kHostGlFunctions[i].name, name))",
        "\t\t\treturn kHostGlFunctions[i].function;",
        "\treturn 0;",
        "}",
    ]
    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
