#!/usr/bin/env python3
"""Generate the Switch host's hostgl_<name> -> real GLES3 function table.

Unlike Android (tools/android_gl_stubs.py's --host-table exclusion: it
resolves GL names at runtime via dlsym against a dynamically loaded
libGLESv3.so), this host statically links devkitPro's real libGLESv2.a/
libEGL.a - the real symbols are already link-time addresses, so a plain
name->&function table needs no runtime lookup at all.

Usage: switch_gl_resolve.py gl_imports.list output.c
"""

import sys


# The hostgl_ names below are hand-written in host_shader_stats.c, every other
# one resolves straight to real GLES3. hostgl_glShaderSource is an ABI adapter
# (build/switch/gen/guest_gl.c truncates each string pointer to 32 bits before
# widening it into a 64-bit slot, so the host unpacks the array itself); the
# rest time the game's shader work and record every program it links - its
# sources and its attribute bindings exactly as made - for the shader warm-up
# (PORTING.md, "Shaders").
CACHE_FUNCTIONS = (
    "hostgl_glShaderSource",
    "hostgl_glCompileShader", "hostgl_glGetShaderiv",
    "hostgl_glBindAttribLocation", "hostgl_glLinkProgram",
)


def main():
    imports_list, output = sys.argv[1:3]
    names = [line.split("#", 1)[0].strip() for line in open(imports_list, encoding="utf-8")]
    names = [n for n in names if n]
    out = [
        "/* generated by tools/switch_gl_resolve.py from build/switch/gen/gl_imports.list; do not edit */",
        "#include <EGL/egl.h>",
        "#include <GLES3/gl32.h>",
        "#include <GLES2/gl2ext.h>",
        "#include <string.h>",
        "",
        "/* hand-written in host_shader_cache.c: the shader pack (programs",
        "compiled ahead on another core, the game's program names mapped to",
        "them, deferred compiles) and glShaderSource's unwrapping of the",
        "guest's widened string pointers */",
        *[f"extern char {n}[];" for n in CACHE_FUNCTIONS],
        "",
        "static const struct { const char *name; void *function; } kHostGlFunctions[] = {",
    ]
    for name in names:
        if name in CACHE_FUNCTIONS:
            out.append(f'\t{{"{name}", (void *){name}}},')
            continue
        real = name[len("hostgl_"):]
        out.append(f'\t{{"{name}", (void *){real}}},')
    out += [
        "};",
        "",
        "void *host_gl_resolve(const char *name)",
        "{",
        "\tfor (unsigned long i = 0; i < sizeof(kHostGlFunctions) / sizeof(kHostGlFunctions[0]); i++)",
        "\t\tif (!strcmp(kHostGlFunctions[i].name, name))",
        "\t\t\treturn kHostGlFunctions[i].function;",
        "\treturn 0;",
        "}",
    ]
    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
